### ISSUE TITLE
Why did you set the value of 100, and is there a possibility that random balls can't be sorted？

### ISSUE THREAD

**Issue by kinlik233** [ragnoril/BallSort#1]
RandomizeBallsInTubes(100);

    }

    public void RandomizeBallsInTubes(int randAmount)
    {
        for(int i=0; i < randAmount; i++)
        {
            int pickTubeIdA = Random.Range(0, Tubes.Count);
            TubeAgent pickTubeA = Tubes[pickTubeIdA];
            while (pickTubeA.BallCount == 0)

Why did you set the value of 100, and is there a possibility that random balls can't be sorted？

**Comment by ragnoril** [comment]
It was an arbitrary choice, I just felt 100 times enough for scrambling all the balls. I could have find some formula based on how many balls and tubes current level have and calculate good number for scrambling all the balls but in reality this works as fine.
